@startuml Caso De Uso

left to right direction
actor "Persona" as Persona
actor "MiembroComunidad" as MiembroComunidad
actor "DesignadoEmpresa" as DesignadoEmpresa
actor "Tiempo (t=1 semana)" as Tiempo

rectangle "Sistema de Monitoreo de Estado de Servicios" {
Persona -- (Configurar Notificaciones)

MiembroComunidad -- (Abrir Incidente)
MiembroComunidad -- (Cerrar Incidente Resuelto)
MiembroComunidad -- (Obtener Listado de Incidentes Reportados)
MiembroComunidad -- (Indicar Afectado u Observador)

DesignadoEmpresa -- (Obtener Rankings)
DesignadoEmpresa -- (Informar Incidente)

Tiempo  -- (Enviar Notificaciones)

}
@enduml