@startuml GenerarRankings



abstract RankingEntidadesQueUsanIncidentes implements RankingEntidades{
    + nombre(): String
    + generarRanking(List<Entidad>): List<Entidad>
    - obtenerIncidenteDeEntidad(Entidad): List<Incidente>
}

class MayorCantidad extends RankingEntidadesQueUsanIncidentes {
    + nombre(): String
    + generarRanking(List<Entidad>): List<Entidad>
    - cantidadDeIncidentesEnLaSemana(Entidad): int
    - incidenteNoOcurrioHace24Hs(Incidente, List<Incidente>): boolean
}




class MayorTiempo extends RankingEntidadesQueUsanIncidentes {
    + nombre(): String
    - promedioTiempoDeCierre(Entidad): float
    + generarRanking(List<Entidad>): List<Entidad>
}


class ImpactoComunidades implements RankingComunidades {
    + nombre(): String
    + generarRanking(List<Comunidad>): List<Comunidad>
    - calcularImpacto(Comunidad): float
}

interface RankingEntidades {
    + nombre(): String
    + generarRanking(List<Entidad>): List<Entidad>
}

interface RankingComunidades {
    + nombre(): String 
    + generarRanking(List<Comunidad>): List<Comunidad>
}

class generadorDatosRanking {

    - rankingsEntidades: List<RankingEntidad>
    - rankingsComunidades: List<RankingComunidad>

    + generarDatos(List<Entidad>, List<Comunidad>): List<List<String>>
    
}

note left of generadorDatosRanking::generarDatos
    formato: 
    [[nombreRanking1, valor1, valor2],
    [nombreRanking2, valor1, valor2],
    [nombreRanking3, valor1, valor2]]

end note



class Exportador {

    - datos: generadorDatosRanking
    - estrategiaDeExportacion: PuedeExportar

    + exportar(List<Entidad>, List<Comunidad>): void

}

interface PuedeExportar {
    + exportar(List<List<String>>): void
}

class ExportarCSV implements PuedeExportar {
    + exportar(List<List<String>>): void
}

note left of ExportarCSV::exportar
    formato: 
    nombreRanking1, nombreRanking2, nombreRanking3
    valor11, valor21, valor31
    valor12, valor22, valor32
    valor13, valor23, valor33
end note


Exportador --> PuedeExportar
Exportador --> generadorDatosRanking
generadorDatosRanking-->RankingEntidades
generadorDatosRanking-->RankingComunidades


@enduml
