@startuml

!define RECTANGLE class

node "Client PC" {
  [Web Browser] as Browser
}

node "Servidor de Aplicacion" as server {
  
node "Aplicacion" {
  [Controller] as controller
  [Repositorios] as repos
  [Javalin] as javalin
  [Vistas] as vistas
  node "Modelos" {
    [Lógica de negocios] as negocios
    [Adapters] as adapters
  }
  [Hibernate] as hibernate
  [Retrofit] as retrofit
}
}

node "Base de datos" {
  [Motor MySQL] as db
  database Database {
  }
}

node "Servidor de Aplicacion" as server1 {
  [Georef] as georef
}

node "Servidor de Aplicacion" as server2 {
  [ServicioRankings] as rankings  
}



retrofit --> georef : API REST
retrofit --> rankings : API REST
Browser --> controller : HTTP
controller --> repos
controller --> javalin
controller --> vistas
controller --> negocios : Uses
negocios --> adapters
repos --> hibernate
hibernate --> db
db --> Database
adapters --> retrofit

@enduml
