@startuml

entity "Usuario" as eUsuario{
  id_usuario: number <<generated>>
  --
  nombre : varchar(255)
  apellido : varchar(255)
  correo : varchar(255)
  contraseña : varchar(255)
  configuracionDeNotificaciones_id : BIGINT,FK
  rol_id : BIGINT,FK
  UbicacionExacta_id : BIGINT,FK

}

entity "usuario_incidente" as eUsuarioIncidente{
  usuario_id : BIGINT,FK
  revisionDeIncidentes_id : BIGINT,FK
}

entity "membresia" as eMembresia{
  id_membresia: number <<generated>>
  --
  comunidad_id : BIGINT,FK
  rol_id : BIGINT,FK
  usuario_id : BIGINT,FK
}

entity "comunidad" as eComunidad{
  id_comunidad: number <<generated>>
  --
  nombre : varchar(255)
  notificador: varchar(255)
}

entity "rol" as eRol{
  id_rol: number <<generated>>
  --
  nombre : varchar(255)
  tipo: varchar(255)
}

entity "rol_permiso" as eRolPermiso{
  rol_id : BIGINT,FK,PK
  permiso_id : BIGINT,FK,PK
}



entity "organismo_de_control" as eOrganismoDeControl{
  id_organismo_de_control: number <<generated>>
  --
  nombre : varchar(255)
  personaDesignada_id : BIGINT,FK
}

entity "entidad_prestadora" as eEntidadPrestadora{
  id_entidad_prestadora: number <<generated>>
  --
  nombre : varchar(255)
  personaDesignada_id : BIGINT,FK
  organismo_de_control_id : BIGINT,FK
}

entity "establecimiento" as eEstablecimiento{
  id_establecimiento: number <<generated>>
  --
  nombre : varchar(255)
  localizacion_id : BIGINT,FK
  entidad_id : BIGINT,FK
}

entity "entidad" as eEntidad{
  id_entidad: number <<generated>>
  --
  nombre : varchar(255)
  localizacion_id : BIGINT,FK
  entidad_prestadora_id : BIGINT,FK
}

entity "afectacion" as eAfectacion{
  id_afectacion: number <<generated>>
  --
  afectado : 
  prestacionDeServicio_ID : BIGINT,FK
  membresia_ID : BIGINT,FK
}

entity "prestacion_de_servicio" as ePrestacionDeServicio{
  id_prestacion_de_servicio: number <<generated>>
  --
  nombre : varchar(255)
  servicio_id : BIGINT,FK
  UbicacionExacta_id: BIGINT,FK
  establecimiento_id : BIGINT,FK
}

entity "localizacion" as eLocalizacion{
  id_localizacion: number <<generated>>
  --
  localidad_id : BIGINT,FK
  municipio_id : BIGINT,FK
  provincia_id : BIGINT,FK
  usuario_id : BIGINT,FK
}

entity "localidad" as eLocalidad{
  id_localidad: number <<generated>>
  --
  nombre : varchar(255)
  municipio_id : BIGINT,FK
  provincia_id : BIGINT,FK
}

entity "municipio" as eMunicipio{
  id_municipio: number <<generated>>
  --
  nombre : varchar(255)
  provincia_id : BIGINT,FK
}

entity "provincia" as eProvincia{
  id_provincia: number <<generated>>
  --
  nombre : varchar(255)
}

entity "ubicacion_exacta" as eUbicacionExacta{
  id_ubicacion_exacta: number <<generated>>
  --
  latitud : DOUBLE
  longitud : DOUBLE
}

entity "interes" as eInteres{
  id_interes: number <<generated>>
  --
  entidad_id : BIGINT,FK
  servicio_id : BIGINT,FK
  usuario_id : BIGINT,FK
}

entity "permiso" as ePermiso{
  id_permiso: number <<generated>>
  --
  nombre : varchar(255)
  nombreInterno : varchar(255)
}

entity "horarios" as eHorarios{
  sinApuros_id : BIGINT,FK
  horario : DATETIME(6)
}

entity "incidente" as eIncidente{
  id_incidente: number <<generated>>
  --
  fecha_de_apertura : DATETIME(6)
  notificador : varchar(255)
  observaciones : LONGTEXT  
  abiertoPor_id : BIGINT,FK
  prestacion_de_servicio_id : BIGINT,FK
}

entity "informe" as eInforme{
  id_informe: number <<generated>>
  --
  fecha : DATE
  nombre : varchar(255)
  path: varchar(255)
}

entity "notificacion" as eNotificacion{
  id_notificacion: number <<generated>>
  --
  asunto : varchar(255)
  cuerpo : varchar(255)
  estrategia_de_notificacion_id : varchar(255)
  destinatario_id : BIGINT,FK
}

entity "estrategiadenotificacion_notificacion" as eEstrategiadenotificacionNotificacion{
  sinApuros_id : BIGINT,FK
  aNotificar_id : BIGINT,FK
}

entity "configuracion_de_notificaciones" as eConfiguracionDeNotificaciones{
  id_configuracion_de_notificaciones: number <<generated>>
  --
  metodo_preferido : varchar(255)
  estrategiaDeNotificacion_id : BIGINT,FK
}

entity "estrategia_de_notificacion" as eEstrategiaDeNotificacion{
  id_estrategia_de_notificacion: number <<generated>>
  --
  nombre : varchar(255)
  descripcion : varchar(255)
}

entity "comunidad_prestacion_de_servicio" as eComunidadPrestacionDeServicio{
  comunidad_id : BIGINT,FK
  servicioDeInteres_id : BIGINT,FK
}

entity "servicio" as eServicio{
  id_servicio: number <<generated>>
  --
  nombre : varchar(255)
}

entity "revision_de_incidente" as eRevisionDeIncidente{
  id_revision_de_incidente: number <<generated>>
}

entity "fechas_de_cierra" as eFechasDeCierra{
  incidente_id : BIGINT,FK
  fechasDeCierre : DATETIME(6)
}

entity "incidente_de_comunidad" as eIncidenteDeComunidad{
  id_incidente_de_comunidad: number <<generated>>
  --
  estado : BIT(1)
  fechas_de_cierre: DATETIME(6)
  cerradoPor_id : BIGINT,FK
  incidente_id : BIGINT,FK
  comunidad_id : BIGINT,FK
}

entity "fusion" as eFusion{
  fusion_id: number <<generated>>
  --
  estado : varchar(255)
  fecha_creada : DATETIME(6)
  comunidad1_id : BIGINT,FK
  comunidad2_id : BIGINT,FK
}

entity "configuraciones" as eConfiguraciones{
  id_configuraciones: number <<generated>>
  --
 api_georef : varchar(255)
 path_csv_organismos : varchar(255)
 path_csv_prestadoras : varchar(255)
 frecuencia_ranking : INT
 latitud_maxima : DOUBLE
 longitud_maxima : DOUBLE
 path_informes : varchar(255)
 path_peores_contrasenias : varchar(255)
}

eUsuario}|--||eUbicacionExacta
eUsuario}|--||eRol
eUsuario}|--||eConfiguracionDeNotificaciones

eMembresia}|--||eRol
eMembresia}|--||eUsuario
eMembresia}|--||eComunidad

eLocalizacion}|--||eMunicipio
eLocalizacion}|--||eUsuario
eLocalidad||-|{eLocalizacion

eProvincia||--|{eLocalizacion

eLocalidad}|--||eMunicipio
eLocalidad}|--||eProvincia

eMunicipio}|--||eProvincia

eInteres}|--||eEntidad
eInteres}|--||eServicio
eInteres}|--||eUsuario

eUsuarioIncidente}|--||eUsuario
eUsuarioIncidente}|--||eIncidente

eIncidente}|--||ePrestacionDeServicio
eIncidente}|--||eUsuario

ePrestacionDeServicio}|--||eServicio
ePrestacionDeServicio}|--||eUbicacionExacta
ePrestacionDeServicio}|--||eEstablecimiento

eEstablecimiento}|--||eEntidad
eEstablecimiento}|--||eLocalizacion

eRolPermiso}|--||eRol
eRolPermiso}|--||ePermiso

eFechasDeCierra}|--||eIncidente

eFusion}|--||eComunidad
eFusion}|--||eComunidad

' eNotificacion}|--||eUsuario
eUsuario||-|{eNotificacion

eEstrategiadenotificacionNotificacion }|--|| eEstrategiaDeNotificacion
eEstrategiadenotificacionNotificacion }|--|| eNotificacion

eOrganismoDeControl}|--||eUsuario

eEntidadPrestadora}|--||eOrganismoDeControl
eEntidadPrestadora}|--||eUsuario

eEntidad}|--||eLocalizacion
eEntidad}|-||eEntidadPrestadora

eIncidenteDeComunidad }|--|| eIncidente
eIncidenteDeComunidad }|--|| eComunidad
eIncidenteDeComunidad }|--|| eUsuario

eHorarios }|--|| eEstrategiaDeNotificacion

eComunidadPrestacionDeServicio }|--|| eComunidad
eComunidadPrestacionDeServicio }|--|| ePrestacionDeServicio

eAfectacion }|--|| eMembresia
eAfectacion }|--|| ePrestacionDeServicio
@enduml